http://localhost:3000/block-number

###

http://localhost:3000/chain-social/user/0x4c2E0165CA1123608CFf84f7805B6C57Be9C3813

###

http://localhost:3000/chain-social/post/1
###
POST http://localhost:3000/chain-social/confirm/create-post
Content-Type: application/json

{
  "transactionHash": "0x0ea1eedc6dab1320e523c15abc17613bb92d7ac04ce12eaa93b3ec6772268864"
}
###
GET http://localhost:3000/data/posts-with-offset-and-limit/0/20
###
POST http://localhost:3000/chain-social/simulate/like-post
Content-Type: application/json

{
  "postId": 1
}
###
GET http://localhost:3000/data/post/422
###
GET http://localhost:3000/data/user-posts/0xC7A0c405DF55943E37d76B1E3c67FdD6518b26f3
###
POST http://localhost:3000/chain-social/simulate/create-post
Content-Type: application/json

{
  "content": "Hello, world!",
  "userAddress": "0x4c2e0165ca1123608cff84f7805b6c57be9c3813"
}
